# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Skiarea.create(location: "12901", name: "Beartown Ski Area")
Skiarea.create(location: "14424", name: "Bristol Mountain")
Skiarea.create(location: "12441", name: "Belleayre Mountain")
Skiarea.create(location: "14551", name: "Brantling Ski and Snowboard Center")
Skiarea.create(location: "14033", name: "Buffalo Ski Club")
Skiarea.create(location: "12529", name: "Catamount Ski Area")
Skiarea.create(location: "13035", name: "Cazenovia Ski Club")
Skiarea.create(location: "14723", name: "Cockaigne Ski Area")
Skiarea.create(location: "13601", name: "Dry Hill Ski Area")
Skiarea.create(location: "13066", name: "Four Seasons Golf and Ski Center")
Skiarea.create(location: "12853", name: "Gore Mountain")
Skiarea.create(location: "13045", name: "Greek Peak")
Skiarea.create(location: "12885", name: "Hickory Ski Center")
Skiarea.create(location: "12701", name: "Holiday Mountain")
Skiarea.create(location: "14731", name: "Holiday Valley")
Skiarea.create(location: "14731", name: "HoliMont")
Skiarea.create(location: "14512", name: "Hunt Hollow Ski Club")
Skiarea.create(location: "12442", name: "Hunter Mountain")
Skiarea.create(location: "14069", name: "Kissing Bridge")
Skiarea.create(location: "13158", name: "Labrador Mountain")
Skiarea.create(location: "12306", name: "Maple Ski Ridge")
Skiarea.create(location: "13420", name: "McCauley Mountain")
Skiarea.create(location: "12983", name: "Mount Pisgah")
Skiarea.create(location: "10990", name: "Mt. Peter Ski Area")
Skiarea.create(location: "12164", name: "Oak Mountain Ski Center")
Skiarea.create(location: "14724", name: "Peek'n Peak Resort")
Skiarea.create(location: "12474", name: "Plattekill")
Skiarea.create(location: "12095", name: "Royal Mountain Ski Area")
Skiarea.create(location: "13473", name: "Snow Ridge Ski Area")
Skiarea.create(location: "13159", name: "Song Mountain")
Skiarea.create(location: "14884", name: "Swain Resort")
Skiarea.create(location: "12563", name: "Thunder Ridge Ski Area")
Skiarea.create(location: "12953", name: "Titus Mountain")
Skiarea.create(location: "13063", name: "Toggenburg Mountain")
Skiarea.create(location: "12804", name: "West Mountain Ski Center")
Skiarea.create(location: "12997", name: "Whiteface Mountain")
Skiarea.create(location: "12834", name: "Willard Mountain")
Skiarea.create(location: "12496", name: "Windham Mountain")
Skiarea.create(location: "13486", name: "Woods Valley Ski Area")


puts "done seeding"
